language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: true
deploy:
  provider: npm
  email: jeremy@tenfourty.com
  api_key:
    secure: HHwi7nSF4bQT6r8NCS/i989vmdp9wvQZhkZUoWlhwiEhakZsWhXKg8mLWERf+l0DMnMKwmQgH6+tLW6nOTJwFiYG1l6PbNH+RsLYnuV91SUeP9iLXihwKdgLBflsEFY91ur/pM0GlwoChBL7Q/HrPFXx353ViEHpyBAkY9tbzQiAg+tVRncF91sKimMxfhqmSnSHmGRbXhn3pibzli483OiPAwoZgGE3fKWQg/pTbP8YJC330efdy6xHUjeXJq0lUtbXDzf4GkJ8q+SqdlPxmSRDbln/Nhw0S0UgkXkqbgvm9VaPVzrX+n6hQFNlJUHBLzZvfPB5W0ENXZOqfwU8QgsSrxDgVwTrCx/tekl9tKDJpEUhZF3pta1UjAWtWvcYFPC0Zs1NuLpiod1yxCkGkPxvJCPu2XeUaZTGDcGQkpY9EvMyN+DdK9ZqEbJCOQeN1cwgA9d8+D070tTdlMlbc5jmQBRN0lgUQCErrWtfFELekl4slmY4QqLvabn0+54OH53PWIorKZmEpfQzFFsvLR/ylQ69wLYzW8Z2jfvbkCqP0/HVmS/p+rdH+djPAbFMFiKBeb5Qe1KooikqK1fj800pnEJe5SDEtIq8jadxdwIFP14OSJlSJvyq8zl1tNhmM5NihQWJ9N6EjcMNVXK36m99azrlJt56J/eVGWOS53w=
  on:
    repo: tenfourty/hubot-scripts-stock
