language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: true
deploy:
  provider: npm
  email: jeremy@tenfourty.com
  api_key:
    secure: GYgE4BuE5i3aNVLh4q/wrtj0/Q0xU2t1QY9ag9Q9kg6CxwoMtW0dou0Q8mvqurSvuKU++zas5JjbUbCMhlzIcxaoevtB5JVvcBQ/TvdX+2wXpguEEZ4xi4WhNAbpY0C3tgi67fkfzFTRgLr13fuCiAKCS+XT/F00uOVKHBQCW0S5EFPZbSBKVlz8fvs3TU7rfLth5rLi2J3w2eDr47uLaajqF6JXU1thJmnlMd2e6cWfLkBHRe9g95eFJ/HaxZMJjKlNR/nhxq300H5cPUEt4TnTvRQMkmJZrxcKIbVmo+KrQ5gXpeCAj8PyOe9OYXXo9erkPs+6hP/z6v+vapo5UqJayCEfpD4gHvJQi2mvkhJR3eW9xq0qd0kq998Mjs3sYaV/zweePezxO5jYp7/v/FZB93XMhHqMKsFVhd0A6bxShZKWCnoDtjHs93mVj2geQwlCDlnA0tEr/8mFT7jOY09gzKrN1wU/iA3pDN0KsQ1iAgdg+x6p5khq2IIiiC565ABBNqyvlT5fuiiNo+EcHxt/9MUC7jP2hTJcwwXWiYFfRlNvG0hihcg235ucql23MeWBPoBx2htObAOHqmkTm+mYPWOaHmLuOV2qmFYOzulnmRd40wK02P6K9dFfrY9wERKToms8CW1ljsvHXITO9+4nAgB7hcw/FtPPzX25Mus=
  on:
    repo: tenfourty/hubot-scripts-stock
